#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
FROM php:7.3.18-fpm-alpine

MAINTAINER Qi Yang <i@yangqi.me>

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#
# Installing tools and PHP extentions using "apt", "docker-php", "pecl",
#

RUN apk add --no-cache \
    autoconf \
    g++ \
    libtool \
    make \
    freetype \
    libpng \
    libjpeg-turbo \
    freetype-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install zip \
    && docker-php-ext-configure gd \
    --with-gd \
    --with-jpeg-dir=/usr/include \
    --with-freetype-dir=/usr/include \
    --with-png-dir=/usr/include \
    && docker-php-ext-install gd \
    && apk del \
    autoconf \
    g++ \
    gcc \
    m4 \
    make \
    libtool \
    pkgconf \
    pkgconfig \
    perl